site:
  title: SoftGate Docs
  start_page: docs::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_paths:
      - softgate-docs
      - softgate-legal
ui:
  supplemental_files:
  - path: partials/header-content.hbs
    contents: ./supplemental-ui/partials/header-content.hbs
  - path: app-ads.txt
    contents: ./src/static/app-ads.txt
  - path: ui.yml
    contents: ./src/ui.yml
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
